### ISSUE TITLE
Generator should normalize problem characters in class names

### ISSUE THREAD

**Issue by blzaugg** [metal/generator-metal#7]
Generator should normalize problem characters in class names.

Note, any problem characters should be normalized, not just the two cases highlighted here.

# Case 1 (spaces)
 1. `$ yo metal`
 1. `? How do you want to name your class? (Modal)`
 2. Enter: `invalid name`
 3. Follow prompts.

**Expected Result:**
Class name to be normalized to one of:
 - `invalidname`
 - `invalidName`
 - `invalid_name`

**Actual Result:**
Generator throws error:
```
npm ERR! install Couldn't read dependencies
npm ERR! Error: Invalid name: "metal-invalid name"
npm ERR!     at ensureValidName (D:\Apps\nodist\bin\node_modules\npm\node_modules\read-package-json\node_modules\no
rmalize-package-data\lib\fixer.js:302:15)
npm ERR!     at Object.module.exports.fixNameField (D:\Apps\nodist\bin\node_modules\npm\node_modules\read-package-j
son\node_modules\normalize-package-data\lib\fixer.js:206:5)
npm ERR!     at D:\Apps\nodist\bin\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-d
ata\lib\normalize.js:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (D:\Apps\nodist\bin\node_modules\npm\node_modules\read-package-json\node_modules\normaliz
e-package-data\lib\normalize.js:28:15)
npm ERR!     at final (D:\Apps\nodist\bin\node_modules\npm\node_modules\read-package-json\read-json.js:342:33)
npm ERR!     at then (D:\Apps\nodist\bin\node_modules\npm\node_modules\read-package-json\read-json.js:126:33)
npm ERR!     at D:\Apps\nodist\bin\node_modules\npm\node_modules\read-package-json\read-json.js:266:40
npm ERR!     at tryToString (fs.js:415:3)
npm ERR!     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:402:12)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "D:\\Apps\\nodist\\v\\nodev5.2.0\\node.exe" "D:\\Apps\\nodist\\bin\\node_modules\\npm\\bin\\npm-cl
i.js" "install"
npm ERR! cwd D:\liferay\metaljs
npm ERR! node -v v5.2.0
npm ERR! npm -v 1.4.6
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\liferay\metaljs\npm-debug.log
npm ERR! not ok code 0
```

# Case 2 (hyphens/minus)
 1. `$ yo metal`
 1. `? How do you want to name your class? (Modal)`
 2. Enter: `invalid-name`
 3. Follow prompts.

**Expected Result:**
Class name to be normalized to one of:
 - `invalidname`
 - `invalidName`
 - `invalid_name`

**Actual Result:**
Generates files like malformed syntax.

demos\index.html:
```html
<script type="text/javascript">
	new metal.Invalid-name();
</script>
```

src\Invalid-name.js:
```js
class Invalid-name extends Component {
}
Soy.register(Invalid-name, templates);

export default Invalid-name;
```

src\Invalid-name.soy:
```soy
{namespace Invalid-name}
```

test\Invalid-name.js:
```js
import Invalid-name from '../src/Invalid-name';
```

**Comment by blzaugg** [comment]
Rather than normalize, maybe we could validate using https://www.npmjs.com/package/inquirer
